CREATE TABLE training_records (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '训练记录ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    device_id BIGINT NOT NULL COMMENT '设备ID',
    training_plan_id BIGINT NOT NULL COMMENT '训练计划ID',
    session_id BIGINT NOT NULL COMMENT '课节ID',
    training_date DATE NOT NULL COMMENT '训练日期',
    start_time DATETIME NOT NULL COMMENT '开始时间',
    end_time DATETIME COMMENT '结束时间',
    duration INT COMMENT '实际训练时长(秒)',
    planned_duration INT COMMENT '计划训练时长(秒)',
    training_type VARCHAR(50) COMMENT '训练类型',
    intensity_level INT COMMENT '强度等级',
    completion_rate DECIMAL(5,2) COMMENT '完成率',
    calories_burned DECIMAL(6,2) COMMENT '消耗卡路里',
    max_heart_rate INT COMMENT '最大心率',
    avg_heart_rate INT COMMENT '平均心率',
    training_data JSON COMMENT '训练数据(JSON格式)',
    user_feedback TEXT COMMENT '用户反馈',
    comfort_level TINYINT COMMENT '舒适度评分(1-10)',
    effectiveness_rating TINYINT COMMENT '效果评分(1-10)',
    status ENUM('completed', 'interrupted', 'failed') DEFAULT 'completed' COMMENT '训练状态',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    FOREIGN KEY (training_plan_id) REFERENCES user_training_plans(id) ON DELETE CASCADE,
    INDEX idx_user_date (user_id, training_date),
    INDEX idx_plan_date (training_plan_id, training_date)
) COMMENT='训练记录表';