CREATE TABLE session_stage_configs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '配置ID',
    session_id BIGINT NOT NULL COMMENT '课节ID',
    stage_order INT NOT NULL COMMENT '阶段顺序',
    stage_name VARCHAR(50) NOT NULL COMMENT '阶段名称',
    stage_type ENUM('warmup', 'main_training', 'cooldown', 'rest') NOT NULL COMMENT '阶段类型',
    duration INT NOT NULL COMMENT '阶段时长(秒)',
    intensity_level INT COMMENT '强度等级(1-10)',
    frequency DECIMAL(5,2) COMMENT '频率(Hz)',
    pulse_width INT COMMENT '脉宽(μs)',
    current_amplitude DECIMAL(5,2) COMMENT '电流幅度(mA)',
    waveform_type VARCHAR(20) COMMENT '波形类型',
    contraction_time INT COMMENT '收缩时间(秒)',
    relaxation_time INT COMMENT '放松时间(秒)',
    repetitions INT COMMENT '重复次数',
    rest_interval INT COMMENT '休息间隔(秒)',
    audio_file_url VARCHAR(500) COMMENT '音频文件URL',
    video_file_url VARCHAR(500) COMMENT '视频文件URL',
    instruction_text TEXT COMMENT '指导文本',
    parameters JSON COMMENT '其他参数(JSON格式)',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (session_id) REFERENCES course_sessions(id) ON DELETE CASCADE,
    UNIQUE KEY uk_session_stage (session_id, stage_order)
) COMMENT='课节内容阶段训练配置表';