CREATE TABLE user_training_plans (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '训练计划ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    device_id BIGINT NOT NULL COMMENT '设备ID',
    plan_name VARCHAR(100) NOT NULL COMMENT '计划名称',
    plan_type ENUM('rehabilitation', 'maintenance', 'enhancement') NOT NULL COMMENT '计划类型',
    target_condition VARCHAR(100) COMMENT '目标病症',
    difficulty_level ENUM('beginner', 'intermediate', 'advanced') DEFAULT 'beginner' COMMENT '难度等级',
    total_sessions INT NOT NULL COMMENT '总课节数',
    completed_sessions INT DEFAULT 0 COMMENT '已完成课节数',
    total_duration INT NOT NULL COMMENT '总时长(分钟)',
    completed_duration INT DEFAULT 0 COMMENT '已完成时长(分钟)',
    start_date DATE COMMENT '开始日期',
    end_date DATE COMMENT '结束日期',
    expected_completion_date DATE COMMENT '预期完成日期',
    current_stage ENUM('basic', 'intermediate', 'advanced') DEFAULT 'basic' COMMENT '当前阶段',
    progress_percentage DECIMAL(5,2) DEFAULT 0.00 COMMENT '完成进度百分比',
    status ENUM('active', 'paused', 'completed', 'cancelled') DEFAULT 'active' COMMENT '计划状态',
    doctor_id BIGINT COMMENT '指导医生ID',
    notes TEXT COMMENT '备注信息',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE SET NULL
) COMMENT='用户设备训练计划管理表';