CREATE TABLE course_sessions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '课节ID',
    session_name VARCHAR(100) NOT NULL COMMENT '课节名称',
    session_code VARCHAR(50) UNIQUE NOT NULL COMMENT '课节编码',
    training_type VARCHAR(50) NOT NULL COMMENT '训练类型',
    category ENUM('electrical_stimulation', 'kegel_exercise', 'music_relaxation', 'game_interaction') NOT NULL COMMENT '方案分类',
    difficulty_level ENUM('beginner', 'intermediate', 'advanced') DEFAULT 'beginner' COMMENT '难度等级',
    duration INT NOT NULL COMMENT '时长(分钟)',
    description TEXT COMMENT '课节描述',
    objectives TEXT COMMENT '训练目标',
    precautions TEXT COMMENT '注意事项',
    target_muscle_groups VARCHAR(200) COMMENT '目标肌群',
    suitable_conditions VARCHAR(200) COMMENT '适用病症',
    contraindications VARCHAR(200) COMMENT '禁忌症',
    min_age INT COMMENT '最小适用年龄',
    max_age INT COMMENT '最大适用年龄',
    gender_restriction ENUM('male', 'female', 'both') DEFAULT 'both' COMMENT '性别限制',
    version VARCHAR(10) DEFAULT '1.0.0' COMMENT '版本号',
    status ENUM('active', 'inactive', 'draft') DEFAULT 'draft' COMMENT '状态',
    created_by BIGINT COMMENT '创建者ID',
    approved_by BIGINT COMMENT '审核者ID',
    approved_at DATETIME COMMENT '审核时间',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) COMMENT='课节内容主表';