CREATE TABLE course_training_plans (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '课程计划ID',
    plan_name VARCHAR(100) NOT NULL COMMENT '计划名称',
    plan_code VARCHAR(50) UNIQUE NOT NULL COMMENT '计划编码',
    target_user_profile TEXT COMMENT '目标用户画像',
    suitable_conditions VARCHAR(200) COMMENT '适用病症',
    plan_description TEXT COMMENT '计划描述',
    total_sessions INT NOT NULL COMMENT '总课节数',
    total_duration INT NOT NULL COMMENT '总时长(分钟)',
    difficulty_progression ENUM('linear', 'adaptive', 'custom') DEFAULT 'linear' COMMENT '难度递进方式',
    frequency_per_week INT COMMENT '每周频次',
    estimated_weeks INT COMMENT '预估周数',
    success_criteria TEXT COMMENT '成功标准',
    plan_objectives TEXT COMMENT '计划目标',
    version VARCHAR(10) DEFAULT '1.0.0' COMMENT '版本号',
    status ENUM('active', 'inactive', 'draft') DEFAULT 'draft' COMMENT '状态',
    created_by BIGINT COMMENT '创建者ID',
    approved_by BIGINT COMMENT '审核者ID',
    approved_at DATETIME COMMENT '审核时间',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) COMMENT='课程训练计划配置主表';